### ISSUE TITLE
Repo Review

### ISSUE THREAD

**Issue by jburel** [ome/omeroweb-install#1]
This issue is a placeholder for comments on the ongoing work

**Comment by jburel** [comment]
1. cf ``https://github.com/aleksandra-tarkowska/omeroweb-install/blob/master/.travis/before_install.sh`` `` sudo apt-get -y install shunit2`` is not needed unless you are also thinking to move the unit tests i.e. ``https://github.com/ome/omero-install/blob/develop/linux/test/test_utils.sh`` or planning to add unit test

**Comment by jburel** [comment]
Discussed this morning with @joshmoore: we won't attend to support 5.1.x in this new repo.
This will simplify some of the files (nginx installation file)

**Comment by aleksandra-tarkowska** [comment]
> Maybe move django-redis-cache>=1.6.5 to a requirement file so it matches the strategy discussed a while back for omero-install

Please note Redis is still experimental. At the moment I would like to keep it as it is.

**Comment by aleksandra-tarkowska** [comment]
>     I do not feel comfortable that we "drop" apache w/o announcement/deprecation. This point needs to be discussed. Warning deprecation in openmicroscopy/openmicroscopy#4805 means that we can only remove it in 5.4

Apache is deprecated. Once this repo become stable I am happy to add one extra more test for apache. Apache is not going away yet.

**Comment by aleksandra-tarkowska** [comment]
> https://github.com/aleksandra-tarkowska/omeroweb-install/blob/master/test/test_services.sh

    docker run -d --privileged -p 8888:80 --name $CNAME $CNAME $WEBPORT should be used

I don't understand that logic, could you explain what you mean exactly?

**Comment by jburel** [comment]
I mean that you allow to pass the webport but it is no use in the command

**Comment by jburel** [comment]
@aleksandra-tarkowska: 
 * understood for redis
 * for apache: I did not update the comment after adding the openmicroscopy PR. If the repo is "accepted", we will need the apache work (as you said) unless we have a 5.2.6 out that we could announce the apache deprecation

**Comment by aleksandra-tarkowska** [comment]
> docker run -d --privileged -p 8888:80 --name $CNAME $CNAME $WEBPORT

but you pass port on building container, start doesn't need any args, as all is already set up.

**Comment by jburel** [comment]
if I have did not used port 80 then ``docker run -d --privileged -p 8888:80 --name $CNAME $CNAME`` will not work unless I am missing something in the other files.

**Comment by jburel** [comment]
I see you expose 
``EXPOSE 22 80 `` in the docker file

**Comment by jburel** [comment]
- [ ] in ``test_ansible`` the default is ``WEBPREFIX=${WEBPREFIX:-/omero}``, in ``test_services`` it is ``WEBPREFIX=${WEBPREFIX:-}``, this could lead to problem for ``{WEBPORT}${WEBPREFIX}`` and ``8888${WEBPREFIX}``

**Comment by jburel** [comment]
I like the organisation os/folder this will should be easier to update/follow up

**Comment by aleksandra-tarkowska** [comment]
> in test_ansible the default is WEBPREFIX=${WEBPREFIX:-/omero}, in test_services it is WEBPREFIX=${WEBPREFIX:-}, this could lead to problem for {WEBPORT}${WEBPREFIX} and 8888${WEBPREFIX}

No, all is fine

no prefix then `/` is taken from `/webclient...` there are enough slashes

```
http://${DOCKER_IP}:${WEBPORT}${WEBPREFIX}/webclient/login/
```

**Comment by aleksandra-tarkowska** [comment]
clean means delete previously generated scripts, this means running ansible playbook again where output is yellow, not green

**Comment by aleksandra-tarkowska** [comment]
I think all the are now addressed

**Comment by jburel** [comment]
cf. https://github.com/aleksandra-tarkowska/omeroweb-install/issues/1#issuecomment-244077859 I did not think about that.

**Comment by jburel** [comment]
I will fetch the latest changes thanks

**Comment by jburel** [comment]
Further improvements can be done if/when we moved it out of TRIAL (doc, etc.)
Thanks @aleksandra-tarkowska

**Comment by jburel** [comment]
Closing this issue since the work has been done
